### ISSUE TITLE
Do_load instruction for 32 bit.

### ISSUE THREAD

**Issue by sanket2608** [seldridge/rocket-rocc-examples#19]
Hi,
I've implemented 32 bit rocket chip with rocc example, but in accumulator example while accessing data through hella cache interface using do_load instruction. The io_mem_response_valid signal remains high for two clock cycle so data in reg file is overwritten by data of next memory location.

![Screenshot from 2020-01-13 18-49-30](https://user-images.githubusercontent.com/45789497/72260008-d7cf2700-3637-11ea-827b-eea39582a0db.png)

May be memory response interface default setting to transfer 64 byte or else. please assist me. how to change burst size?

Thanks & Regards,
Sanket

**Comment by seldridge** [comment]
(Without verifying) I think what's going on is that the underlying data is still 64-bit. I'm not sure if this is supposed to happen or if this is an artifact of how your Rocket Chip system is configured. When the Rocket Chip configuration switches to 32-bit, then a 64-bit DCache response will be delivered over two cycles. You would need to modify the accumulator RoCC so that it properly handles this situation of a 64-bit response coming back.

The simplest solution would be to wait for two responses and then only use the first (though this is obviously wrong generally). You can see where that's getting written here:
https://github.com/chipsalliance/rocket-chip/blob/94d2a8e7ea702d427c94e57eddbea8ddef575a59/src/main/scala/tile/LazyRoCC.scala#L148

Alternatively, you may be able to change Rocket Chip's configuration to be fully 32-bit under the hood. However, that's more of a Rocket Chip configuration question.

**Comment by sanket2608** [comment]
Thanks for reply,

> Alternatively, you may be able to change Rocket Chip's configuration to be fully 32-bit under the hood. However, that's more of a Rocket Chip configuration question.

May be this is not adequate place for this thread. 
Sorry but i couldn't get it. I implemented 32 bit rocket core with tiny configuration.All data buses and registers are 32 bits. Is there anything else to do?  

I went through one berkeley's lab documentation for **accelerator:matrix sum**; There they have mentioned while sending data over hella cache request and response interface you need to give specific value for **typ** signal(e.g. typ = 011 for 64 bits).
I think i need to send typ signal with interface which is not specify in [https://github.com/chipsalliance/rocket-chip/blob/94d2a8e7ea702d427c94e57eddbea8ddef575a59/src/main/scala/tile/LazyRoCC.scala#L148](url)  and not even in [https://github.com/chipsalliance/rocket-chip/blob/94d2a8e7ea702d427c94e57eddbea8ddef575a59/src/main/scala/rocket/HellaCache.scala ](url)


If I'm right can you give me values for typ signal in order to specify it's 32 bit transaction.I'm trying to find it out but not success xD.


Thanks & Regards,
Sanket

**Comment by sanket2608** [comment]
Sorry to say i also added typ=010 to io mem interface but it's not part of hellacache interface exception asserted..

**Comment by sanket2608** [comment]
there is signal io.mem.req.bit.size in [https://github.com/chipsalliance/rocket-chip/blob/94d2a8e7ea702d427c94e57eddbea8ddef575a59/src/main/scala/tile/LazyRoCC.scala](url) I just changed it's value to 2 (it was log2Ceil(8).U which is 3 ).and now io.mem.resp.valid is high for one clock cycle. 
Issue resolved !!!.
